OUTER_SET FLAG_SAVINGTHROW_spell = BIT0
OUTER_SET FLAG_SAVINGTHROW_breath = BIT1
OUTER_SET FLAG_SAVINGTHROW_death = BIT2
OUTER_SET FLAG_SAVINGTHROW_wand = BIT3
OUTER_SET FLAG_SAVINGTHROW_polymorph = BIT4

// TobEx
OUTER_SET FLAG_SAVINGTHROW_limit_effect_stacking_Ex = BIT25
// OUTER_SET FLAG_SAVINGTHROW_tobex_suspend_stacking_application = BIT26 // internal

// EE games
OUTER_SET FLAG_SAVINGTHROW_ignore_primary_target_EE = BIT10	// Line AoE projectile doesn't affect end target
OUTER_SET FLAG_SAVINGTHROW_ignore_secondary_target_EE = BIT11	// Line AoE projectile doesn't affect bystanders
OUTER_SET FLAG_SAVINGTHROW_bypass_mirror_image_EE = BIT24
OUTER_SET FLAG_SAVINGTHROW_ignore_difficulty_EE = BIT25
