/**
 * BG2 barrel re-exports.
 *
 * Uses named re-exports (not export *) so esbuild can statically resolve each
 * binding without falling back to runtime __reExport helpers for externalized
 * .d.ts modules.
 */

// --- Actions (generated from IESDP) ---
export {
  ActionOverride, Activate, AddAreaFlag, AddAreaType, AddExperienceParty,
  AddExperiencePartyGlobal, AddFamiliar, AddGlobals, AddJournalEntry, AddKit,
  AddMapNote, AddSpecialAbility, AddSuperKit, AddXP2DA, AddXPObject, Ally,
  AmbientActivate, AnkhegEmerge, AnkhegHide, ApplyDamage, ApplyDamagePercent,
  ApplySpell, ApplySpellRES, AttachTransitionToDoor, Attack, AttackNoSound,
  AttackOneRound, AttackReevaluate, BanterBlockFlag, BanterBlockTime, BashDoor,
  BattleSong, CallLightning, Calm, ChangeAIScript, ChangeAIType, ChangeAlignment,
  ChangeAnimation, ChangeAnimationNoEffect, ChangeClass, ChangeEnemyAlly,
  ChangeGender, ChangeGeneral, ChangeRace, ChangeSpecifics, ChangeTileState,
  ClearActions, ClearAllActions, CloseDoor, ContainerEnable, Continue,
  CopyGroundPilesTo, CreateCreature, CreateCreatureAtLocation,
  CreateCreatureCopyPoint, CreateCreatureDoor, CreateCreatureImpassable,
  CreateCreatureImpassableAllowOverlap, CreateCreatureObject,
  CreateCreatureObjectCopy, CreateCreatureObjectCopyEffect,
  CreateCreatureObjectDoor, CreateCreatureObjectEffect,
  CreateCreatureObjectOffScreen, CreateCreatureObjectOffset,
  CreateCreatureOffScreen, CreateItem, CreateItemGlobal, CreateItemNumGlobal,
  CreateVisualEffect, CreateVisualEffectObject, CutAllowScripts, CutSceneId,
  DayNight, Deactivate, DemoEnd, DestroyAllDestructableEquipment,
  DestroyAllEquipment, DestroyGold, DestroyItem, DestroySelf, DetectSecretDoor,
  Dialog, DialogForceInterrupt, DialogInterrupt, Dialogue,
  DialogueForceInterrupt, DialogueInterrupt, DisplayString, DisplayStringHead,
  DisplayStringHeadDead, DisplayStringHeadOwner, DisplayStringNoName,
  DisplayStringNoNameHead, DisplayStringWait, DropInventory, DropItem,
  EndCredits, EndCutSceneMode, Enemy, EquipItem, EquipMostDamagingMelee,
  EquipRanged, EraseJournalEntry, EscapeArea, EscapeAreaDestroy, EscapeAreaMove,
  EscapeAreaNoSee, EscapeAreaObject, EscapeAreaObjectMove, ExitPocketPlane,
  Explore, Face, FaceObject, FadeFromColor, FadeToColor, FakeEffectExpiryCheck,
  FillSlot, FindTraps, FlyToPoint, Follow, FollowObjectFormation, ForceSpell,
  ForceSpellPoint, ForceSpellPointRange, ForceSpellPointRangeRES,
  ForceSpellPointRES, ForceSpellRange, ForceSpellRangeRES, ForceSpellRES,
  Formation, GiveGoldForce, GiveItem, GiveItemCreate, GiveOrder,
  GivePartyAllEquipment, GivePartyGold, GivePartyGoldGlobal, GlobalShout,
  GoToStartScreen, GroupAttack, Hide, HideAreaOnMap, HideGUI, IncrementChapter,
  IncrementGlobal, Interact, JoinParty, JumpToPoint, Kill, Leader, LeaveArea,
  LeaveAreaLUA, LeaveAreaLUAEntry, LeaveAreaLUAPanic, LeaveAreaLUAPanicEntry,
  LeaveAreaName, LeaveParty, Lock, LockScroll, MakeGlobal, MakeUnselectable,
  MoraleDec, MoraleInc, MoraleSet, MoveBetweenAreas, MoveBetweenAreasEffect,
  MoveGlobal, MoveGlobalObject, MoveGlobalObjectOffScreen, MoveGlobalsTo,
  MoveToCenterOfScreen, MoveToExpansion, MoveToObject, MoveToObjectFollow,
  MoveToObjectNoInterrupt, MoveToOffset, MoveToPoint, MoveToPointNoInterrupt,
  MoveToSavedLocation, MoveToSavedLocationn, MoveViewObject, MoveViewPoint,
  MultiPlayerSync, NoAction, OpenDoor, Panic, PauseGame, PickLock, PickPockets,
  PickUpItem, PlayDead, PlayDeadInterruptable, PlayDeadInterruptible,
  PlayerDialog, PlayerDialogue, PlaySong, PlaySound, Polymorph, PolymorphCopy,
  PolymorphCopyBase, ProtectObject, ProtectPoint, RandomFly, RandomTurn,
  RandomWalk, RandomWalkContinuous, ReallyForceSpell, ReallyForceSpellDead,
  ReallyForceSpellDeadRES, ReallyForceSpellPoint, ReallyForceSpellPointRES,
  ReallyForceSpellRES, RealSetGlobalTimer, Recoil, RegainPaladinHood,
  RegainRangerHood, RemoveAreaFlag, RemoveAreaType, RemoveFamiliar,
  RemoveMapNote, RemovePaladinHood, RemoveRangerHood, RemoveSpell,
  RemoveSpellRES, RemoveTraps, ReputationInc, ReputationSet, Rest, RestNoSpells,
  RestorePartyLocations, RestParty, RevealAreaOnMap, RunAwayFrom,
  RunAwayFromNoInterrupt, SaveGame, SaveLocation, SaveObjectLocation,
  ScreenShake, SelectWeaponAbility, SendTrigger, SetAreaRestFlag,
  SetBeenInPartyFlags, SetCursorState, SetCutSceneLite, SetDialog, SetDialogue,
  SetEncounterProbability, SetGabber, SetGlobal, SetGlobalTimer,
  SetHomeLocation, SetInterrupt, SetLeavePartyDialogFile,
  SetLeavePartyDialogueFile, SetMasterArea, SetName, SetNumTimesTalkedTo,
  SetPlayerSound, SetQuestDone, SetRestEncounterProbabilityDay,
  SetRestEncounterProbabilityNight, SetSequence, SetToken, SetTokenGlobal,
  SetTokenObject, SetupWish, SetupWishObject, SG, Shout, SmallWait,
  SoundActivate, SpawnPtActivate, SpawnPtDeactivate, SpawnPtSpawn, Spell,
  SpellNoDec, SpellNoDecRES, SpellPoint, SpellPointNoDec, SpellPointNoDecRES,
  SpellPointRES, SpellRES, StartCombatCounter, StartCutScene,
  StartCutSceneMode, StartDialog, StartDialogInterrupt, StartDialogNoName,
  StartDialogNoSet, StartDialogNoSetInterrupt, StartDialogOverride,
  StartDialogue, StartDialogueInterrupt, StartDialogueNoSet,
  StartDialogueNoSetInterrupt, StartMovie, StartMusic, StartRainNow,
  StartStore, StartTimer, StateOverrideFlag, StateOverrideTime, StaticPalette,
  StaticSequence, StaticStart, StaticStop, StorePartyLocations, Swing,
  SwingOnce, TakeItemListParty, TakeItemListPartyNum, TakeItemReplace,
  TakePartyGold, TakePartyItem, TakePartyItemAll, TakePartyItemNum,
  TakePartyItemRange, TextScreen, TriggerActivation, Turn, UndoExplore,
  UnhideGUI, Unlock, UnlockScroll, UseContainer, UseDoor, UseItem, UseItemSlot,
  UseItemSlotAbility, VEquip, VerbalConstant, VerbalConstantHead, Wait,
  WaitWait, Weather,
} from './actions';

// --- IDS types and constants ---
export type { Align } from './align.ids.d';

export type { Animate } from './animate.ids.d';
export {
  FIRE_RING, CHUNKS, EXPLODING_ARM, EXPLODING_HEAD, EXPLODING_FOOT,
  EXPLODING_TORSO, EXPLODING_LEG, SMOKE_PUFF_LARGE, SMOKE_PUFF_SMALL,
  TRAP_SKULL, TRAP_GLYPH, CLOUD_TRAVEL, CLOUD_STATIC, STORM_TRAVEL,
  STORM_STATIC, GREASE_TRAVEL, GREASE_STATIC, WEB_TRAVEL, WEB_STATIC,
  WYVERN_BIG, TANARRI, DRAGON_RED, DRAGON_BLACK, DRAGON_SILVER, DRAGON_GREEN,
  DRAGON_AQUA, DRAGON_BLUE, DRAGON_BROWN, DRAGON_MULTICOLOR, DRAGON_PURPLE,
  DEMIGORGON, SIRINE, VOLO, OGRE_MAGE, DEATH_KNIGHT, ANKHEG,
  STATIC_NOBLE_MAN_CHAIR, STATIC_NOBLE_MAN_MATTE, STATIC_NOBLE_WOMAN_CHAIR,
  STATIC_NOBLE_WOMAN_MATTE, STATIC_PEASANT_MAN_CHAIR,
  STATIC_PEASANT_MAN_STOOL, STATIC_PEASANT_MAN_MATTE,
  STATIC_PEASANT_WOMAN_CHAIR, STATIC_PEASANT_WOMAN_MATTE,
  STATIC_HUMANCLERIC_MAN_CHAIR, STATIC_SPIDER_WOMAN, SLEEPING_MAN_HUMAN,
  SLEEPING_WOMAN_HUMAN, SLEEPING_FAT_MAN_HUMAN, SLEEPING_DWARF,
  SLEEPING_MAN_ELF, SLEEPING_WOMAN_ELF, SLEEPING_MAN_HALFLING,
  CLERIC_MALE_HUMAN_LOW, CLERIC_MALE_ELF_LOW, CLERIC_MALE_DWARF_LOW,
  CLERIC_MALE_HALFLING_LOW, CLERIC_FEMALE_HUMAN_LOW, CLERIC_FEMALE_ELF_LOW,
  CLERIC_FEMALE_DWARF_LOW, CLERIC_FEMALE_HALFLING_LOW, FIGHTER_MALE_HUMAN_LOW,
  FIGHTER_MALE_ELF_LOW, FIGHTER_MALE_DWARF_LOW, FIGHTER_MALE_HALFLING_LOW,
  FIGHTER_FEMALE_HUMAN_LOW, FIGHTER_FEMALE_ELF_LOW, FIGHTER_FEMALE_DWARF_LOW,
  FIGHTER_FEMALE_HALFLING_LOW, MAGE_MALE_HUMAN_LOW, MAGE_MALE_ELF_LOW,
  MAGE_MALE_DWARF_LOW, MAGE_FEMALE_HUMAN_LOW, MAGE_FEMALE_ELF_LOW,
  MAGE_FEMALE_DWARF_LOW, THIEF_MALE_HUMAN_LOW, THIEF_MALE_ELF_LOW,
  THIEF_MALE_DWARF_LOW, THIEF_MALE_HALFLING_LOW, THIEF_FEMALE_HUMAN_LOW,
  THIEF_FEMALE_ELF_LOW, THIEF_FEMALE_DWARF_LOW, THIEF_FEMALE_HALFLING_LOW,
  CLERIC_MALE_HUMAN, CLERIC_MALE_ELF, CLERIC_MALE_DWARF, CLERIC_MALE_HALFLING,
  CLERIC_MALE_GNOME, CLERIC_MALE_HALFORC, CLERIC_FEMALE_HUMAN,
  CLERIC_FEMALE_ELF, CLERIC_FEMALE_DWARF, CLERIC_FEMALE_HALFLING,
  CLERIC_FEMALE_GNOME, CLERIC_FEMALE_HALFORC, FIGHTER_MALE_HUMAN,
  FIGHTER_MALE_ELF, FIGHTER_MALE_DWARF, FIGHTER_MALE_HALFLING,
  FIGHTER_MALE_GNOME, FIGHTER_MALE_HALFORC, FIGHTER_FEMALE_HUMAN,
  FIGHTER_FEMALE_ELF, FIGHTER_FEMALE_DWARF, FIGHTER_FEMALE_HALFLING,
  FIGHTER_FEMALE_GNOME, FIGHTER_FEMALE_HALFORC, MAGE_MALE_HUMAN, MAGE_MALE_ELF,
  MAGE_MALE_DWARF, MAGE_MALE_GNOME, MAGE_MALE_HALFORC, MAGE_FEMALE_HUMAN,
  MAGE_FEMALE_ELF, MAGE_FEMALE_DWARF, MAGE_FEMALE_GNOME, MAGE_FEMALE_HALFORC,
  THIEF_MALE_HUMAN, THIEF_MALE_ELF, THIEF_MALE_DWARF, THIEF_MALE_HALFLING,
  THIEF_MALE_GNOME, THIEF_MALE_HALFORC, THIEF_FEMALE_HUMAN, THIEF_FEMALE_ELF,
  THIEF_FEMALE_DWARF, THIEF_FEMALE_HALFLING, THIEF_FEMALE_GNOME,
  THIEF_FEMALE_HALFORC, MONK_MALE_HUMAN, MONK_FEMALE_HUMAN, DRIZZT, ELMINSTER,
  MONK, SKELETON, SAREVOK, DOOM_GUARD, DOOM_GUARD_LARGER, HALF_OGRE, OGRILLON,
  BASILISK, BASILISK_GREATER, BEAR_BLACK, BEAR_BROWN, BEAR_CAVE, BEAR_POLAR,
  ELEMENTAL_EARTH, ELEMENTAL_EARTH_SMALL, SHAMBLING_MOUND, ELEMENTAL_FIRE,
  ELEMENTAL_FIRE_SMALL, ELEMENTAL_FIRE_PURPLE, ELEMENTAL_FIRE_SMALL_PURPLE,
  BURNING_MAN, ELEMENTAL_AIR, ELEMENTAL_AIR_SMALL, DOG_WILD, DOG_WAR, DOG_MOON,
  DOPPLEGANGER, DOPPLEGANGER_GREATER, ETTERCAP, GHOUL, REVEANT, GHAST, SHADOW,
  GIBBERLING, SLIME_GREEN, SLIME_OLIVE, SLIME_MUSTARD, SLIME_OCHRE, GRAY_OOZE,
  SPIDER_GIANT, SPIDER_HUGE, SPIDER_PHASE, SPIDER_SWORD, SPIDER_WRAITH, WOLF,
  WOLF_WORG, WOLF_DIRE, WOLF_WINTER, WOLF_VAMPIRE, WOLF_DREAD, WOLF_SHADOW,
  KOBOLD_XVART, KOBOLD_TASLOI, ZOMBIE, WEREWOLF, WEREWOLF_GREATER, TROLL,
  MINDFLAYER, BEHOLDER, IMP, GOLEM_IRON, DJINNI, DJINNI_LEGS, GOLEM_CLAY,
  OTYUGH, SAHAUGIN, GREATCAT_PANTHER, GREATCAT_LEOPARD, LICH, DEMILICH,
  TROLL_SMALL, RAKSHASA, UMBER_HULK, VAMPIRE, SNAKE, GITHYANKI, BEHOLDER_SMALL,
  MOOSE, RABBIT, DEER, DANCING_SWORD, GROUNDHOG, PHEASANT, VAMPIRE_FEMALE,
  SAHAUGIN_LARGE, PIRATE, DROW, DROW_FEMALE, SAILOR_MAN, MDK2_MAX,
  AMISH_SOLDIER, WYVERN_FAMILIAR, RAVER, SPIDER_SMALL, BODHI, ELLESIME, SLAYER,
  MDK2_KURT, MDK2_DOCTOR, MIST_CREATURE, SHADOW_THIEF, JON_IRENICUS,
  BLOB_MIST_CREATURE, HULA_WIZARD, SOLAR, ANTISOLAR, MELISSAN, FIRE_GIANT,
  GNOLL, HOBGOBLIN, KOBOLD, OGRE, WYVERN, CARRION_CRAWLER, COW, HORSE,
  STATIC_BEGGAR_MAN, STATIC_HARLOT_WOMAN, STATIC_BOY, STATIC_GIRL,
  STATIC_FAT_MAN, STATIC_FAT_WOMAN, STATIC_PEASANT_MAN, STATIC_PEASANT_WOMAN,
  STATIC_NOBLE_MAN, STATIC_NOBLE_WOMAN, STATIC_SLAVE, BAT_INSIDE, CAT, CHICKEN,
  RAT, SQUIRREL, BAT_OUTSIDE, BEGGAR_MAN, HARLOT_WOMAN, BOY, GIRL, FAT_MAN,
  FAT_WOMAN, PEASANT_MAN, PEASANT_WOMAN, NOBLE_MAN, NOBLE_WOMAN, SLAVE, EAGLE,
  SEAGULL, VULTURE, BIRD, BIRD_INSIDE, IC_ETTIN, DONOT_USE, IC_LICHBLACK,
  IC_MINOTAUR, IC_MUMMY, IC_MERILITH, IC_TROLL1, IC_CORNUGONSKI, IC_ICE_GOLEM,
  IC_GLAB, IC_WAILING_VIRGIN, IC_GOBLIN_AXE, IC_GOBLIN_BOW,
  IC_GOBLINELITE_AXE, IC_GOBLINELITE_BOW, IC_LIZARDCASTER1, IC_MYCONID,
  IC_MYCONID2, IC_OROG1, IC_OROG2, IC_OROG3, IC_ORC_MELEE1, IC_ORC_RANGE2,
  IC_ORC_MELEE3, IC_ORC_RANGE4, IC_ORC_SHAMAN, IC_SALAMANDER, IC_SALAMANDER2,
  IC_SHROOM, IC_SKELETON0, IC_SKELETONA, IC_SKELETONB, IC_YUANTI, IC_YUANTI2,
  IC_YUANTI3,
} from './animate.ids.d';

export type { AreaFlag } from './areaflag.ids.d';
export type { AreaTypeID } from './areatype.ids.d';

export type { AStyles } from './astyles.ids.d';
export { DEFAULT, MELEE, RANGED } from './astyles.ids.d';

export type { ClassID } from './class.ids.d';
export type { Damages } from './damages.ids.d';
export { Direction } from './dir.ids';
export type { DiffLev } from './difflev.ids.d';
export type { DMGtype } from './dmgtype.ids.d';

export type { EA } from './ea.ids.d';
export { ENEMY } from './ea.ids.d';

export type { GenderID } from './gender.ids.d';
export type { GeneralID } from './general.ids.d';
export type { GTimes } from './gtimes.ids.d';
export type { Happy } from './happy.ids.d';
export type { HotKeyID } from './hotkey.ids.d';
export type { JourType } from './jourtype.ids.d';
export type { KitID } from './kit.ids.d';
export type { MFlags } from './mflags.ids.d';

export type { Modal } from './modal.ids.d';
export { NONE, BATTLESONG, DETECTTRAPS, STEALTH, TURNUNDEAD } from './modal.ids.d';

export type { NPC } from './npc.ids.d';

// --- Object identifiers ---
export {
  Nothing, Myself, LeaderOf, GroupOf, WeakestOf, StrongestOf, MostDamagedOf,
  LeastDamagedOf, ProtectedBy, ProtectorOf, LastAttackerOf, LastTargetedBy,
  LastCommandedBy, Nearest, LastHitter, LastHelp, LastTrigger, Player1, Player2,
  Player3, Player4, Player5, Player6, Protagonist, StrongestOfMale,
  SecondNearest, ThirdNearest, FourthNearest, FifthNearest, SixthNearest,
  SeventhNearest, EighthNearest, NinthNearest, TenthNearest, WorstAC, BestAC,
  LastSummonerOf, NearestEnemyOfType, SecondNearestEnemyOfType,
  ThirdNearestEnemyOfType, FourthNearestEnemyOfType, FifthNearestEnemyOfType,
  SixthNearestEnemyOfType, SeventhNearestEnemyOfType,
  EigthNearestEnemyOfType, NinthNearestEnemyOfType, TenthNearestEnemyOfType,
  NearestMyGroupOfType, SecondNearestMyGroupOfType, ThirdNearestMyGroupOfType,
  FourthNearestMyGroupOfType, FifthNearestMyGroupOfType,
  SixthNearestMyGroupOfType, SeventhNearestMyGroupOfType,
  EigthNearestMyGroupOfType, NinthNearestMyGroupOfType,
  TenthNearestMyGroupOfType, Player1Fill, Player2Fill, Player3Fill, Player4Fill,
  Player5Fill, Player6Fill, NearestDoor, SecondNearestDoor, ThirdNearestDoor,
  FourthNearestDoor, FifthNearestDoor, SixthNearestDoor, SeventhNearestDoor,
  EighthNearestDoor, NinthNearestDoor, TenthNearestDoor,
} from './object.d';
export {
  NearestEnemyOf, LastSeenBy, LastTalkedToBy, LastHeardBy,
  SecondNearestEnemyOf, ThirdNearestEnemyOf, FourthNearestEnemyOf,
  FifthNearestEnemyOf, SixthNearestEnemyOf, SeventhNearestEnemyOf,
  EigthNearestEnemyOf, NinthNearestEnemyOf, TenthNearestEnemyOf,
} from './object';

// --- More IDS types and constants ---
export type { RaceID } from './race.ids.d';
export type { ReactionID } from './reaction.ids.d';
export type { ScrLev } from './scrlev.ids.d';
export type { Scroll } from './scroll.ids.d';
export type { Seq } from './seq.ids.d';

export type { ShoutID } from './shoutids.ids.d';
export { HEALME, ASSIST, ALERT, SOLAR_STANCE } from './shoutids.ids.d';

export type { Slots } from './slots.ids.d';
export {
  SLOT_AMULET, SLOT_ARMOR, SLOT_BELT, SLOT_BOOTS, SLOT_CLOAK, SLOT_GAUNTLETS,
  SLOT_HELMET, SLOT_RING_LEFT, SLOT_RING_RIGHT, SLOT_SHIELD, SLOT_FIST,
  SLOT_AMMO, SLOT_MISC, SLOT_WEAPON, SLOT_AMMO0, SLOT_AMMO1, SLOT_AMMO2,
  SLOT_AMMO3, SLOT_MISC0, SLOT_MISC1, SLOT_MISC2, SLOT_MISC3, SLOT_MISC4,
  SLOT_MISC5, SLOT_MISC6, SLOT_MISC7, SLOT_MISC8, SLOT_MISC9, SLOT_MISC10,
  SLOT_MISC11, SLOT_MISC12, SLOT_MISC13, SLOT_MISC14, SLOT_MISC15,
  SLOT_MISC16, SLOT_MISC17, SLOT_MISC18, SLOT_MISC19, SLOT_WEAPON0,
  SLOT_WEAPON1, SLOT_WEAPON2, SLOT_WEAPON3,
} from './slots.ids.d';

export type { SndSlot } from './sndslot.ids.d';
export type { SoundOff } from './soundoff.ids.d';
export type { Specific } from './specific.ids.d';

export {
  CLERIC_BLESS, CLERIC_COMMAND, CLERIC_CURE_LIGHT_WOUNDS, CLERIC_DETECT_EVIL, CLERIC_ENTANGLE, CLERIC_MAGIC_STONE, CLERIC_PROTECT_FROM_EVIL, CLERIC_REMOVE_FEAR, CLERIC_SANCTUARY, CLERIC_SHILLELAGH, CLERIC_ARMOR_OF_FAITH, CLERIC_DOOM, CLERIC_SPIRIT_WARD, CLERIC_AID, CLERIC_BARKSKIN, CLERIC_CHANT, CLERIC_CHARM_PERSON, CLERIC_FIND_TRAPS, CLERIC_FLAME_BLADE, CLERIC_GOOD_BERRIES, CLERIC_HOLD_PERSON, CLERIC_KNOW_ALIGNMENT, CLERIC_RESIST_FIRE, CLERIC_SILENCE_15_FOOT, CLERIC_SLOW_POISON, CLERIC_SPIRITUAL_HAMMER, CLERIC_DRAW_UPON_HOLY_MIGHT, CLERIC_WRITHING_FOG, CLERIC_ANIMATE_DEAD, CLERIC_CALL_LIGHTNING, CLERIC_DISPEL_MAGIC, CLERIC_GLYPH_OF_WARDING, CLERIC_HOLD_ANIMAL, CLERIC_PROTECTION_FROM_FIRE, CLERIC_REMOVE_CURSE, CLERIC_REMOVE_PARALYSIS, CLERIC_INVISIBILITY_PURGE, CLERIC_MISCAST_MAGIC, CLERIC_RIGID_THINKING, CLERIC_STRENGTH_OF_ONE, CLERIC_HOLY_SMITE, CLERIC_UNHOLY_BLIGHT, CLERIC_CURE_MEDIUM_WOUNDS, CLERIC_CURE_DISEASE, CLERIC_ZONE_OF_SWEET_AIR, CLERIC_SUMMON_INSECTS, CLERIC_SPIRITUAL_CLARITY, CLERIC_CURE_SERIOUS_WOUNDS, CLERIC_ANIMAL_SUMMONING_1, CLERIC_FREE_ACTION, CLERIC_NEUTRALIZE_POISON, CLERIC_MENTAL_DOMINATION, CLERIC_DEFENSIVE_HARMONY, CLERIC_PROTECTION_FROM_LIGHTNING, CLERIC_PROTECTION_FROM_EVIL_10_FOOT, CLERIC_DEATH_WARD, CLERIC_CALL_WOODLAND_BEINGS, CLERIC_POISON, CLERIC_HOLY_POWER, CLERIC_NEGATIVE_PLANE_PROTECTION, CLERIC_CAUSE_SERIOUS_WOUNDS, CLERIC_FAR_SIGHT, CLERIC_CLOAK_OF_FEAR, CLERIC_LESSER_RESTORATION, CLERIC_SPIRIT_FIRE, CLERIC_ANIMAL_SUMMONING_2, CLERIC_CURE_CRITICAL_WOUNDS, CLERIC_FLAME_STRIKE, CLERIC_RAISE_DEAD, CLERIC_TRUE_SIGHT, CLERIC_IRONSKIN, CLERIC_CHAMPIONS_STRENGTH, CLERIC_CHAOTIC_COMMANDS, CLERIC_MAGIC_RESISTANCE, CLERIC_CAUSE_CRITICAL_WOUNDS, CLERIC_SLAY_LIVING, CLERIC_GREATER_COMMAND, CLERIC_RIGHTEOUS_MAGIC, CLERIC_MASS_CURE, CLERIC_REPULSE_UNDEAD, CLERIC_PIXIE_DUST, CLERIC_INSECT_PLAGUE, CLERIC_RECALL_SPIRIT, ENEMY_CLERIC_SLAY_LIVING, CLERIC_AERIAL_SERVANT, CLERIC_ANIMAL_SUMMONING_3, CLERIC_BLADE_BARRIER, CLERIC_CONJURE_ANIMALS, CLERIC_CONJURE_FIRE_ELEMENTAL, CLERIC_FIRE_SEEDS, CLERIC_HEAL, CLERIC_HARM, CLERIC_FALSE_DAWN, CLERIC_DOLOROUS_DECAY, CLERIC_WONDROUS_RECALL, CLERIC_BOLT_OF_GLORY, CLERIC_PHYSICAL_MIRROR, CLERIC_SOL_SEARING_ORB, CLERIC_SPIRITUAL_LOCK, NPC_BLADE_BARRIER, ENEMY_CLERIC_HARM, CLERIC_SHIELD_OF_THE_ARCHONS, CLERIC_CONJURE_EARTH_ELEMENTAL, CLERIC_GATE, CLERIC_NATURE_BEAUTY, CLERIC_FIRE_STORM, CLERIC_SYMBOL_FEAR, CLERIC_SUNRAY, CLERIC_FINGER_OF_DEATH, CLERIC_CONFUSION, CLERIC_HOLY_WORD, CLERIC_REGENERATE, CLERIC_RESURRECTION, CLERIC_RESTORATION, CLERIC_UNHOLY_WORD, CLERIC_CREEPING_DOOM, CLERIC_SYMBOL_STUN, CLERIC_SYMBOL_DEATH, CLERIC_EARTHQUAKE, CLERIC_ENERGY_BLADES, CLERIC_STORM_OF_VENGEANCE, CLERIC_ELEMENTAL_SWARM, CLERIC_GREATER_ELEMENTAL_SWARM, CLERIC_GLOBE_OF_BLADES, CLERIC_SUMMON_DEVA, CLERIC_SUMMON_FALLEN_DEVA, CLERIC_IMPLOSION, CLERIC_MASS_RAISE_DEAD, CLERIC_AURA_OF_FLAMING_DEATH, CLERIC_ELEMENTAL_TRANSFORMATION_FIRE, CLERIC_ELEMENTAL_TRANSFORMATION_EARTH, CLERIC_ETHER_GATE, CLERIC_ETHEREAL_RETRIBUTION, TRAP_DIRE_CHARM, TRAP_CONFUSION, TRAP_CHROMATIC_ORB, TRAP_FLAMESTRIKE, TRAP_MISCAST_MAGIC, TRAP_CALL_LIGHTNING, TRAP_SILENCE, TRAP_HOLD_PERSON, SHOAL_REVIVE, TRAP_FIREBALL, TRAP_LIGHTNING_BOLT, TRAP_MAGIC_MISSILE, TRAP_STINKING_CLOUD, TRAP_ARROW, TRAP_ARROW_SLAYING, TRAP_ARROW_ACID, TRAP_ARROW_BITING, TRAP_ARROW_DETONATION, TRAP_ARROW_DISPELLING, TRAP_ARROW_FIRE, TRAP_ARROW_ICE, TRAP_ARROW_PIERCING, TRAP_MONSTER_SUMMONING, TRAP_FROST, TRAP_CLOUDKILL, TRAP_MINOR_LIGHTNING_BOLT, TRAP_UNDERWATER_BITE, TRAP_HALLWAY_SPIKES, TRAP_MUCK, TRAP_SHADOW_DEATH, TRAP_GUILLOTINE, TRAP_LIGHTNING_ORB1, TRAP_LIGHTNING_ORB2, TRAP_LIGHTNING_ORB3, WIZARD_CHAOS_VISUALS_ONLY, WIZARD_DISPEL_MAGIC_VISUALS_ONLY, WIZARD_POWER_WORD_SILENCE_VISUALS_ONLY, WIZARD_FLESH_TO_STONE_IGNORE_RESISTANCE, WIZARD_FINGER_OF_DEATH_IGNORE_RESISTANCE, WIZARD_DISINTEGRATE_IGNORE_RESISTANCE, WIZARD_DISINTEGRATE2_IGNORE_RESISTANCE, WIZARD_GREASE, WIZARD_ARMOR, WIZARD_BURNING_HANDS, WIZARD_CHARM_PERSON, WIZARD_COLOR_SPRAY, WIZARD_BLINDNESS, WIZARD_FRIENDS, WIZARD_PROTECTION_FROM_PETRIFICATION, WIZARD_IDENTIFY, WIZARD_INFRAVISION, WIZARD_MAGIC_MISSILE, WIZARD_PROTECTION_FROM_EVIL, WIZARD_SHIELD, WIZARD_SHOCKING_GRASP, WIZARD_SLEEP, WIZARD_CHILL_TOUCH, WIZARD_CHROMATIC_ORB, WIZARD_LARLOCH_MINOR_DRAIN, WIZARD_REFLECTED_IMAGE, WIZARD_FIND_FAMILAR, WIZARD_NAHALS_RECKLESS_DWEOMER, WIZARD_SPOOK, WIZARD_BLUR, WIZARD_DETECT_EVIL, WIZARD_DETECT_INVISIBILITY, WIZARD_HORROR, WIZARD_INVISIBILITY, WIZARD_KNOCK, WIZARD_KNOW_ALIGNMENT, WIZARD_LUCK, WIZARD_RESIST_FEAR, WIZARD_MELF_ACID_ARROW, WIZARD_MIRROR_IMAGE, WIZARD_STINKING_CLOUD, WIZARD_STRENGTH, WIZARD_WEB, WIZARD_AGANNAZAR_SCORCHER, WIZARD_GHOUL_TOUCH, WIZARD_VOCALIZE, WIZARD_POWER_WORD_SLEEP, WIZARD_RAY_OF_ENFEEBLEMENT, WIZARD_CHAOS_SHIELD, WIZARD_DEAFNESS, WIZARD_GLITTERDUST, CONTINGENCY_MIRROR_IMAGE, WIZARD_CLAIRVOYANCE, WIZARD_REMOVE_MAGIC, WIZARD_FLAME_ARROW, WIZARD_FIREBALL, WIZARD_HASTE, WIZARD_HOLD_PERSON, WIZARD_INVISIBILITY_10_FOOT, WIZARD_LIGHTNING_BOLT, WIZARD_MONSTER_SUMMONING_1, WIZARD_NON_DETECTION, WIZARD_PROTECTION_FROM_NORMAL_MISSILES, WIZARD_SLOW, WIZARD_SKULL_TRAP, WIZARD_VAMPIRIC_TOUCH, WIZARD_WRAITH_FORM, WIZARD_DIRE_CHARM, WIZARD_GHOST_ARMOR, WIZARD_MINOR_SPELL_DEFLECTION, WIZARD_PROTECTION_FROM_FIRE, WIZARD_PROTECTION_FROM_COLD, WIZARD_SPELL_THRUST, WIZARD_DETECT_ILLUSION, WIZARD_HOLD_UNDEAD, WIZARD_MELF_METEOR, WIZARD_TRUE_DISPEL_MAGIC, WIZARD_CONFUSION, WIZARD_DIMENSION_DOOR, WIZARD_FIRE_SHIELD_BLUE, WIZARD_ICE_STORM, WIZARD_IMPROVED_INVISIBILITY, WIZARD_MINOR_GLOBE_OF_INVULNERABILITY, WIZARD_MONSTER_SUMMONING_2, WIZARD_STONE_SKIN, WIZARD_CONTAGION, WIZARD_REMOVE_CURSE, WIZARD_EMOTION_HOPELESSNESS, WIZARD_GREATER_MALISON, WIZARD_OTILUKES_RESILIENT_SPHERE, WIZARD_SPIRIT_ARMOR, WIZARD_POLYMORPH_OTHER, WIZARD_POLYMORPH_SELF, WIZARD_ENCHANTED_WEAPON, WIZARD_FIRE_SHIELD_RED, WIZARD_SECRET_WORD, WIZARD_MINOR_SEQUENCER, WIZARD_TELEPORT_FIELD, WIZARD_SPIDER_SPAWN, WIZARD_FAR_SIGHT, WIZARD_EYE, WIZARD_POLYMORPH_NATURAL_FORM, WIZARD_POLYMORPH_FLIND, WIZARD_POLYMORPH_OGRE, WIZARD_POLYMORPH_SPIDER, WIZARD_POLYMORPH_MUSTARD_JELLY, WIZARD_POLYMORPH_BROWN_BEAR, WIZARD_POLYMORPH_BLACK_BEAR, WIZARD_POLYMORPH_WOLF, WIZARD_ANIMATE_DEAD, WIZARD_CLOUDKILL, WIZARD_CONE_OF_COLD, WIZARD_MONSTER_SUMMONING_3, WIZARD_SHADOW_DOOR, WIZARD_DOMINATION, WIZARD_HOLD_MONSTER, WIZARD_CHAOS, WIZARD_FEEBLEMIND, WIZARD_SPELL_IMMUNITY, WIZARD_PROTECTION_FROM_NORMAL_WEAPONS, WIZARD_PROTECTION_FROM_ELECTRICITY, WIZARD_BREACH, WIZARD_LOWER_RESISTANCE, WIZARD_ORACLE, WIZARD_CONJURE_LESSER_FIRE_ELEMENTAL, WIZARD_PROTECTION_FROM_ACID, WIZARD_PHANTOM_BLADE, WIZARD_SPELL_SHIELD, WIZARD_CONJURE_LESSER_AIR_ELEMENTAL, WIZARD_CONJURE_LESSER_EARTH_ELEMENTAL, WIZARD_MINOR_SPELL_TURNING, WIZARD_SUN_FIRE, WIZARD_SPELL_IMMUNITY_ABJURATION, WIZARD_SPELL_IMMUNITY_CONJURATION, WIZARD_SPELL_IMMUNITY_DIVINATION, WIZARD_SPELL_IMMUNITY_ENCHANTMENT, WIZARD_SPELL_IMMUNITY_ILLUSIONIST, WIZARD_SPELL_IMMUNITY_INVOCATION, WIZARD_SPELL_IMMUNITY_NECROMANCY, WIZARD_SPELL_IMMUNITY_ALTERATION, WIZARD_INVISIBLE_STALKER, WIZARD_GLOBE_OF_INVULNERABILITY, WIZARD_TENSERS_TRANSFORMATION, WIZARD_FLESH_TO_STONE, WIZARD_DEATH_SPELL, WIZARD_PROTECTION_FROM_MAGIC_ENERGY, WIZARD_MISLEAD, WIZARD_PIERCE_MAGIC, WIZARD_TRUE_SIGHT, WIZARD_PROTECTION_FROM_MAGIC_WEAPONS, WIZARD_POWER_WORD_SILENCE, WIZARD_IMPROVED_HASTE, WIZARD_DEATH_FOG, WIZARD_CHAIN_LIGHTNING, WIZARD_DISINTEGRATE, WIZARD_CONTINGENCY, WIZARD_SPELL_DEFLECTION, WIZARD_WYVERN_CALL, WIZARD_CONJURE_FIRE_ELEMENTAL, WIZARD_CONJURE_AIR_ELEMENTAL, WIZARD_CONJURE_EARTH_ELEMENTAL, WIZARD_CARRION, WIZARD_SUMMON_NISHRUU, WIZARD_STONE_TO_FLESH, WIZARD_SPELL_TURNING, WIZARD_PROTECTION_FROM_THE_ELEMENTS, WIZARD_PROJECT_IMAGE, WIZARD_RUBY_RAY_OF_REVERSAL, WIZARD_WARDING_WHIP, WIZARD_CACOFIEND, WIZARD_MANTLE, WIZARD_SPELL_SEQUENCER, WIZARD_SPHERE_OF_CHAOS, WIZARD_DELAYED_BLAST_FIREBALL, WIZARD_FINGER_OF_DEATH, WIZARD_PRISMATIC_SPRAY, WIZARD_POWER_WORD_STUN, WIZARD_MORDENKAINENS_SWORD, WIZARD_SUMMON_EFREET, WIZARD_SUMMON_DJINNI, WIZARD_SUMMON_HAKEASHAR, WIZARD_CONTROL_UNDEAD, WIZARD_MASS_INVISIBILITY, WIZARD_LIMITED_WISH, WIZARD_IMPROVED_CHAOS_SHIELD, WIZARD_PROTECTION_FROM_ENERGY, WIZARD_SIMULACRUM, WIZARD_PIERCE_SHIELD, WIZARD_SUMMON_FIEND, WIZARD_IMPROVED_MANTLE, WIZARD_SPELL_TRIGGER, WIZARD_INCENDIARY_CLOUD, WIZARD_SYMBOL_FEAR, WIZARD_ABI_DALZIMS_HORRID_WILTING, WIZARD_MAZE, WIZARD_POWER_WORD_BLIND, WIZARD_SYMBOL_STUN, WIZARD_SYMBOL_DEATH, WIZARD_BIGBYS_CLENCHED_FIST, FORCE_DAMAGE_1, WIZARD_NPC_SYMBOL_DEATH, WIZARD_NPC_SYMBOL_STUN, WIZARD_NPC_SYMBOL_FEAR, WIZARD_SPELL_TRAP, WIZARD_SPELL_STRIKE, WIZARD_GATE, WIZARD_ABSOLUTE_IMMUNITY, WIZARD_CHAIN_CONTINGENCY, WIZARD_TIME_STOP, WIZARD_IMPRISONMENT, WIZARD_METEOR_SWARM, WIZARD_POWER_WORD_KILL, WIZARD_WAIL_OF_THE_BANSHEE, WIZARD_ENERGY_DRAIN, WIZARD_BLACK_BLADE_OF_DISASTER, WIZARD_SHAPECHANGE, WIZARD_FREEDOM, WIZARD_BIGBYS_CRUSHING_HAND, WIZARD_WISH, WIZARD_ENERGY_BLADES, WIZARD_IMPROVED_ALUCRITY, WIZARD_DRAGONS_BREATH, WIZARD_SUMMON_PLANATAR_GOOD, WIZARD_SUMMON_PLANATAR_EVIL, WIZARD_COMET, QUICK_TELEPORT, SUCCUBUS_ETHEREAL, SUCCUBUS_ENERGY_DRAIN, SUCCUBUS_CHARM_FEMALE, SUCCUBUS_CHARM_MALE, SUCCUBUS_TELEPORT, TANARI_CHANGE, DURLAG_SWORD, CRUSHING_TRAP, SUMMON_SKELETON_WARRIOR3, SUMMON_SKELETON_WARRIOR2, SUMMON_SKELETON_WARRIOR, CHARM_HERO, FIREDRAKE_DAMAGE, LOVEM_CHANGE, QUEEN_CHANGE, SIRINE_DIRE_CHARM, DAESEWOLF_CHANGE, LOUPGAR_CHANGE, PLAYER_WEREWOLF_CHANGE, GREATER_WOLFWERE_CHANGE, WEREWOLF_CHANGE, WOLFWERE_CHANGE, FAST_SKULLTRAP, JELLY_SPLIT, DRADEEL_FLAMEBLADE, DRADEEL_BLUE_FIREBALL, DRADEEL_MINOR_GLOBE, PAIN, FEAR, RED_FIREBALL, POWERWORD_BLIND, POWERWORD_STUN, POWERWORD_KILL, DOPPLEGANGER_CHANGE4, DOPPLEGANGER_CHANGE5, DOPPLEGANGER_CHANGE6, DOPPLEGANGER_CHANGE7, DOPPLEGANGER_CHANGE8, SAREVOK_STRIKE, FIREBALL_DEATH, MUSHROOM_FIRE, DAERRAGH, RISE_FROM_ASH, RED_SWIRL, RED_HOLY_MIGHT, SPIDER_SUMMON, DOPPLEGANGER_CHANGE_DEFAULT_LESSER, DOPPLEGANGER_CHANGE_DEFAULT, EFFECT_ONLY, DOPPLEGANGER_CHANGE3, DOPPLEGANGER_RASHAD, DOPPLEGANGER_CHANGE2, DOPPLEGANGER_CHANGE, PHASE_SPIDER_TELEPORT, DRYAD_TELEPORT, CHARM_KORAX, GORION_LIGHTNING, GORION_MAGIC_MISSILE, DIETY_KILL, INNATE_CURE_LIGHT_WOUNDS, INNATE_SLOW_POISON, INNATE_DRAW_UPON_HOLY_MIGHT, INNATE_LARLOCHS_MINOR_DRAIN, INNATE_HORROR, INNATE_VAMPIRIC_TOUCH, MINSC_BERSERK, AVENGER_SHAPESHIFT_NATURAL_FORM, DRUID_SHAPESHIFT_FROM_BLACKBEAR, SHAPESHIFTER_SHAPESHIFT_NATURAL_FORM, SHAPESHIFT_NATURAL_FORM_1, SHAPESHIFT_NATURAL_FORM_2, SHAPECHANGE_MIND_FLAYER, SHAPECHANGE_IRON_GOLEM, SHAPECHANGE_GIANT_TROLL, SHAPECHANGE_GREATER_WOLFWERE, SHAPECHANGE_FIRE_ELEMENTAL, SHAPECHANGE_EARTH_ELEMENTAL, SALAMANDER_BREATHE_FIREBALL, ABAZIGAL_SHOCKWAVE, DRAGON_LOWER_ELECTRICAL, SENDAI_CHANGE, SUMMON_DEVIL_SHADE, GREEN_DRAGON_BREATH, LICH_FEAR, TROLL_FIRE_CHANGE, MAJOR_POLYMORPH, FLAMING_SKULL_BOLT, RABBIT_POWER, SAR_DIVINATION, PSIONIC_DISINTEGRATE, PSIONIC_INFLICT_PAIN, PSIONIC_SUPERIOR_INVISIBILITY, PSIONIC_LIFE_DRAIN, PSIONIC_INERTIAL_BARRIER, PSIONIC_PROJECT_FORCE, DEMOGORGON_GATE, SUMMON_INFERNAL_HOST, HIVE_MOTHER_ANTIMAGIC_RAY, HIVE_MOTHER_CAUSE_SERIOUS_WOUNDS, HIVE_MOTHER_DISINTEGRATE, NALMISSRA_CHARM, GAIN_ONE_CHA_PERMANENT, GAIN_ONE_WIS_PERMANENT, GAIN_ONE_INT_PERMANENT, GAIN_ONE_DEX_PERMANENT, ERINYES_CHARM, BURNING_MAN_KEENING, BURNING_MAN_CINDER_SHOWER, FIRE_GIANT_LAVA, ICE_GOLEM_STEAM, HOLY_PILLAR_VISUAL, SKULL_EXPLODE, GAROCK_TELEPORT, MIMIC_WEB, MIMIC_FIRE, MIMIC_POISON, SUMMON_ICE_SALAMANDER, SUMMON_FIRE_ELEMENTAL, SUCCUBUS_KISS, CUTSCENE_HASTE, IMOEN_BHAAL2, IMOEN_BHAAL1, VORTEX_WEB, DENSE_PUDDING_SPLIT, GAIN_ONE_THACO, GAIN_ONE_AC, POWER_AMP, IMPRISONMENT_NO_SAVE, RESTORATION_IGNORE_RESIST, CONFUSION_NO_SAVE, POISON_NO_SAVE, GAIN_HASTE_TEMPORARY, GAIN_MAGIC_RESIST_PERMANENT, LOSE_FIFTEEN_LEVELS, LOSE_FIVE_LEVELS, LOSE_ONE_DEX_PERMANENT, LOSE_ONE_INT_PERMANENT, GAIN_ONE_CON_PERMANENT, GAIN_ONE_STR_PERMANENT, HELM_RITUAL_SCROLL, ODREN_RITUAL_SCROLL, DEMOGORGON_CHANGE, YELLOW_DRAGON_BREATH, BROWN_DRAGON_BREATH, BLUE_DRAGON_BREATH, SAREVOK_FLASHY1, FIRE_HEALING, SAREVOK_SOULSTEAL, SPECIAL_SWEET_AIR, CHROMATIC_DEMON_RED, CHROMATIC_DEMON_WHITE, CHROMATIC_DEMON_GREEN, CHROMATIC_DEMON_YELLOW, DECK_SUN, DECK_JESTER, DECK_VIZIER, DECK_GEM, DECK_FATES, DECK_COMET, DECK_FOOL, DECK_TALONS, DECK_ROGUE, DECK_KNIGHT, DECK_FLAMES, DECK_EURYALE, DECK_MOON, DECK_THRONE, DECK_KEY, DECK_SKULL, DECK_MAGICIAN, DECK_VOID, DECK_RUIN, DECK_DONJON, FROZEN_DEATH, SLOW_FREEZE, DECK_WHEEL, DECK_STRENGTH, DECK_CONSTRUCT, DECK_EMPEROR, DECK_EMPRESS, DECK_HIGH_PRIESTESS, DECK_STRIFE, DECK_DEFIANCE, DECK_GUILE, DECK_TRIUMPH, DECK_PLAGUE, DECK_XP_DRAIN, DECK_VITALITY_DRAIN, POISONOUS_CLOUD, FAN_BLOW, BALOR_FIRE_SHIELD, WILD_MAGIC_AREA, DEAD_MAGIC_AREA, DISPEL_NO_SAVE, HOLD_PERSON_NO_SAVE, ENTER_POCKET_PLANE, DM_SHIELD, DM_SEE_INVISIBLE, DM_MAGIC_PROTECTION, DM_COLD_PROTECTION, DM_FIRE_PROTECTION, DM_IMPROVED_HASTE, VIEKANG_LIGHTNING, DO_SOME_EFFECTS, HELL_BUFFET, TROLL_CHANGE_NITHIRI, POOF_GONE, EDWINA_IN_HELL, EDWIN_CHANGE_BACK, CREATE_YOSHIMO_BLADE, NETHER_SCROLL, BEHOLDER_BLAST_VISUAL2, ZOMBIE_LEVEL_DRAIN, SLAYER_BACK_TO_HUMAN_NOVIS, REMOVE_NON_PERMANENT_DEATH, APPLY_NON_PERMANENT_DEATH, SEA_TROLL_CHANGE, SWOOSH_GONE, QUICK_INVISIBLE, SPORE_DEATH, MIST_CHAOS, MIST_HORROR, INVOKE_COURAGE, SUMMON_POISON, ANOMEN_TITLE, HEAL_NO_VISUAL, HARPER_DEATH_SONG, BANSHEE_WAIL, DRAGON_LOWER_FIRE, FIGURINE_SPIDER_WEB, KOA_TRUE_SIGHT_NO_VIS, MAGIC_MISSILE_SURE_HIT, PROTECTION_MAGIC_WEAPON_NOEFF, SHADOW_DRAGON_SHADOWS, BLACK_DRAGON_PLANT, BLACK_DRAGON_INSECT, HOLY_LIGHT_FROM_ABOVE, BLACK_DRAGON_BREATH, DRAGON_SILENCE, RED_DRAGON_HIT, DRAGON_STONE_SKIN, DRAGON_WING_BUFFET, MOON_DOG_HOWL, HASTE_SELF, NON_DETECTION_SELF, INVISIBILITY_SELF, TROLL_SETHP1, DEATHKNIGHT_FIREBALL, FAKE_FLAME_STRIKE, AERIE_DISPEL_MAGIC, NYMPH_CONFUSION, TRAP_VENT, TRAP_DARTS, TRAP_SLIME, TRAP_SPEAR, SPELL_DEFLECTION_NO_VISUAL, FINAL_HEAL, MULTIPLAYER_ANTIMAGIC, ICE_DUST, CELESTIAL_BOLT, TROLL_RAT_SPAWN, SLAYER_IMMUNE_TO_DAMAGE, SLAYER_CHANGE_CUT_SCENE, SLAYER_BACK_TO_HUMAN, CUTSCENE_METEOR_SWARM, CUTSCENE_DAMAGE_1C, CUTSCENE_DAMAGE_1B, GREAT_DRUID_TITLE, DRAGON_RAIN, RAISSA_RESTORE, SKIN_DANCER_RESTORE_2, CUTSCENE_DAMAGE_1, NOSAVE_PSIONIC_BLAST, SKIN_DANCER_RESTORE, SKIN_DANCER_SWITCH, SUMMON_FUNGUS, WISH_SPELL_FAILURE, WISH_LOSE_SPELL, WISH_POISON, WISH_HEAL_PARTY, WISH_RABBIT, WISH_GLOBE, WISH_MEMORIZE, WISH_PLANE, TROLL_SPECTRAL_CHANGE, TROLL_SNOW_CHANGE, TROLL_SPIRIT_CHANGE, TROLL_GIANT_CHANGE, TROLL_FRESHWATER_CHANGE, TROLL_DESERT_CHANGE, AERIE_PORTRAIT, RESTORE_FULL_HEALTH, HELL_SELFISH_EVIL, HELL_SELFISH_GOOD, HELL_WRATH_EVIL, HELL_WRATH_GOOD, HELL_PRIDE_EVIL, HELL_PRIDE_GOOD, HELL_FEAR_EVIL, HELL_FEAR_GOOD, HELL_GREED_EVIL, HELL_GREED_GOOD, IRENICUS_WORD_OF_POWER, PLAYER1_WORD_OF_POWER, HELL_GAIN_CHR, HELL_GAIN_CON, HELL_GAIN_DEX, HELL_GAIN_WIS, HELL_GAIN_INT, HELL_GAIN_STR, HELL_LOSE_XP, HELL_LOSE_DEX, HELL_LOSE_HP, HELL_DISPELL, HELL_HOLD, HELL_EXPLODE, HELL_DAMAGE_HALF, HELL_FEAR, EVIL_LAYONHANDS, PSIONIC_MAZE, PSIONIC_MIND_BLAST, MAKE_STATUE, BEHOLDER_BLAST_VISUAL, WILD_MAGIC_ZONE, ANTI_MAGIC_ZONE, FLASHY_DEATH_3, FLASHY_DEATH_2, FLASHY_DEATH_1, SLAYER_ENEMY, SNAKE_GAZE, PERM_CHARM, LICH_IMPRISON, SMALL_DAMAGE_SPELL, DEMILICH_TRAP_SOUL, DEMILICH_DEATH, LONG_VISUAL2, TROLL_ICE_CHANGE, LONG_VISUAL, FLASHY_DEATH_YEAH, FLASHY_4, FLASHY_3, FLASHY_2, FLASHY_1, BODHI_BAT_ASYLUM, DACE_FLAME, FLAME_HEAD, NO_FEAR_PARTY, MIND_CRIPPLE, DACE_MIST_FORM_CHANGE, PSIONIC_EMOTION_KILL, THIEF_DETECT_ILLUSION, LICH_REPLACE_SELF, SLAYER_FEAR, DRAIN_PARTY, BODHI_MIST_FORM_CHANGE, GIVE_SLAYER_POWER, VAMPIRE_FORM_CHANGE, DEL_VAMP_FORM_CHANGE, SLAVE_CHUNK, TANOVA_MIST_FORM_CHANGE, DEL_MIST_FORM_CHANGE, VALEN_MIST_FORM_CHANGE, C6BODHI_WEAKNESS, C6VAMPIRE_WEAKNESS, LAVA_BURST, ELVEN_GUARD_WAIL, LONG_RED_MIGHT, SLAYER_START, SLAYER_CHANGE_TWO, DEATH_CURSE, DROW_CHANGE, MAZZY_STRENGTH, MAZZY_LAY, MAZZY_HASTE, JAN_AMMO, UNDER_NORM, UNDER_SQUIRREL, SILVER_DRAGON_BREATH_PARALIZATION, SILVER_DRAGON_BREATH_COLD, BRAIN_PSIONIC_BLAST, ILLUSION_DEATH, JON_ALL_DEAD, JON_WISH, LOSE_ALL, HULK_CONFUSION, BOOK_GOLEM, BOOK_BEHOLD, BOOK_MIND, BOOK_UMBER, BOOK_SPIDER, BOOK_KOBOLD, SAND_DIE, FIRAMB05_CHANGE, DISARM_ENEMY, TROLL_SMALL_CHANGE, DGTROLL_CHANGE, FIRAMB01_CHANGE, SLAYER_CHANGE, FORCE_SPHERE, MAGNET, SUMMON_DJINN_TRAP, SUMMON_DEATH_KNIGHT, SUMMON_PIT_FIEND, ONE_INT, ONE_WIS, ONE_DEX, ONE_CON, NOHOLD_PARTY, HOLD_PARTY, TRANSFORMATION_DEATH, FORCE_STONE_TRAP, FORCE_DISPEL_MAGIC, RED_PILLAR_VISUAL, CERND_CERND, CERND_BEAR, SUMMON_SHADOW_WOLF, END_EXPLORE, FIVE_ROUND_ENCHANTMENT_IMMUNITY, UNPAUSE_CASTER, FALDORN_PANTHER, ANATH_WEREWOLF2, ANATH_WEREWOLF, APPRENTI_DEATH, SHADOW_DRAIN, MAKE_SHADOW, SUMMON_SHADOW, GREATER_WEREWOLF_CHANGE, VAMPIRE_FEAR, VAMPIRE_DOMINATION, CHICKEN_CHANGE, KAMIKAZE_EXPLOSION, RAELIS_OPEN_PORTAL, SUMMONED_MIND, SURE_STONE_SHATTER, SURE_STONED, DEMON_FEAR, MOON_DOG_FEAR, SURE_SLEEP, SHADOW_DRAGON_BREATH, RED_DRAGON_BREATH, DRAGON_FEAR, REPULSE_X, BEHOLDER_GAS_SPORE, ARCHER_PROTECTION, ZOMBIE_SICKNESS, ZOMBIE_CHANGE, ZOMBIE_CON_LOSS, BODVAM02_MIST_CHANGE, BODVAM01_MIST_CHANGE, LASSAL_MIST_CHANGE, DO_NOTHING, THREE_ROUND_ENCHANTMENT_IMMUNITY, FIFTY_PERCENT_DAMAGE_ARROW, FIFTY_PERCENT_DAMAGE, PSIONIC_EGOWHIP, PSIONIC_DOMINATION, PSIONIC_BALLISTIC, PSIONIC_DETONATE, MIMIC_ACID, MIMIC_GLUE, SPIDER_CHANGE, EDWIN_CHANGE, MANE_GAS, HARPASS_CHANGE, JAHEIRA_WEAKNESS, BEHOLDER_SPELL_TURNING, REVENANT_CHANGE, GENIE_LIMITED_WISH_HEAL_ALL, COVER_PARTIAL, COVER_FULL, MEPHIT_WATER_JET, MEPHIT_RAINSTORM, MEPHIT_MIST, MEPHIT_LAVA, MEPHIT_SOOTY_BALL, MEPHIT_BOLT, MEPHIT_LIGHTNING_BOLT, MEPHIT_SALT_CRYSTAL, MEPHIT_GLASS_DUST, MEPHIT_ICE_SHARD, MEPHIT_COLOR_SPRAY, MEPHIT_FLAME_FAN, MEPHIT_FLAME_JET, MEPHIT_STINKING_CLOUD, MEPHIT_SPIT_ROCK, MEPHIT_GRIT, MEPHIT_BLUR, CUTSCENE_POWERWORD_STUN, CUTSCENE_SPELLSTRIKE, CUTSCENE_BREACH, CUTSCENE_MIND_FOG, CUTSCENE_LOWER_RESISTANCE, CUTSCENE_RUBY_RAY_OF_REVERSAL, CUTSCENE_FLESH_TO_STONE, CUTSCENE_POWERWORD_KILL, CUTSCENE_PHANTASMAL_KILLER, CUTSCENE_IMPRISONMENT, SIRINE_TELEPORT_FAKE, TROLL_CHANGE, HELL_HOUND_FLAME, GHOULLORD_FEAR, ULITHARID_CURE_SERIOUS_WOUNDS, ULITHARID_PSIONIC_BLAST, BEHOLDER_PARALYZATION_RAY, BEHOLDER_FINGER_OF_DEATH, BEHOLDER_MAGIC_MISSILE, VAMPIRE_BAT_FORM_CHANGE, VAMPIRE_GAS_FORM_CHANGE, TROLL_HEAL_ONE_HIT_POINT, TROLL_SLEEP, EFREETI_PHYSICAL_FORM_CHANGE, DOA_PHYSICAL_FORM_CHANGE, DJINNI_PHYSICAL_FORM_CHANGE, EFREETI_GAS_FORM_CHANGE, DOA_GAS_FORM_CHANGE, DJINNI_GAS_FORM_CHANGE, AIR_ELEMENTAL_EFFECT, MIND_FLAYER_PSIONIC_BLAST, MIND_FLAYER_DOMINATION, GOLEM_CONFUSION, GOLEM_SLOW, GOLEM_HASTE, GOLEM_GASCLOUD, BEHOLDER_CHARM_PERSON, BEHOLDER_FEAR, BEHOLDER_DISINTEGRATE, BEHOLDER_SLOW, BEHOLDER_FLESH_TO_STONE, BEHOLDER_DOMINATION, BEHOLDER_CAUSE_SERIOUS_WOUNDS, BEHOLDER_AGANNAZAR_SCORCHER, BEHOLDER_HOLD_PERSON, BEHOLDER_LIGHTNING_BOLT, BEHOLDER_PARALYZATION, BEHOLDER_DEATH_RAY, BEHOLDER_ANTIMAGIC_RAY, ACID_DAMAGE_1, TANARI_DEATH_GAZE, TANARI_VAMPIRIC_TOUCH, TANARI_SILENCE, TANARI_PARALYZE, BLACKGUARD_ABSORB_HEALTH, AURA_OF_DESPAIR, RESIST_FEAR, IMMUNITY_TO_LEVEL_DRAIN, BLACKGUARD_ANIMATE_DEAD, ARCHER_CALL_SHOT, KENSAI_KIA, BARBARIAN_RAGE, PALADIN_LAY_ON_HANDS, PALADIN_DETECT_EVIL, PALADIN_PROTECTION_FROM_EVIL, CAVALIER_REMOVE_FEAR, INQUIS_DISPEL_MAGIC, INQUIS_TRUE_SIGHT, SUN_SOUL_SUN_SOULRAY, SUN_SOUL_GREATER_SUN, SUN_SOUL_SUN_SOULBEAM, RANGER_CHARM_ANIMAL, BERSERKER_RAGE, BEASTMASTER_FIND_FAMILIAR, THIEF_SET_SNARE, THIEF_SET_SPECIAL_SNARE, ASSASSIN_POISON, BLADE_OFFENSIVE_SPIN, BLADE_DEFENSIVE_SPIN, DRUID_SHAPESHIFT_BROWNBEAR, DRUID_SHAPESHIFT_WOLF, DRUID_SHAPESHIFT_BLACKBEAR, TOTEMIC_DRUID_SUMMON_SPIRIT_ANIMAL, AVENGER_SHAPESHIFT_SWORDSPIDER, AVENGER_SHAPESHIFT_BABYWYVERN, AVENGER_SHAPESHIFT_FIRESALAMANDER, SHAPESHIFTER_SHAPESHIFT_WEREWOLF, SHAPESHIFTER_SHAPESHIFT_GREATERWEREWOLF, TALOS_STORMSHIELD, TALOS_LIGHTNING_BOLT, HELM_SEEKING_SWORD, HELM_TRUE_SIGHT, LATHANDER_BOON, LATHANDER_HOLD_UNDEAD, MONK_STUNNING_BLOW, MONK_LAY_ON_HANDS, MONK_QUIVERING_PALM, WARRIOR_WHIRLWIND, WARRIOR_GREATER_WHIRLWIND, WARRIOR_DEATHBLOW, WARRIOR_GREATER_DEATHBLOW, WARRIOR_RESIST_MAGIC, WARRIOR_CRITICAL_STRIKE, WARRIOR_POWER_ATTACK, WARRIOR_HARDINESS, WARRIOR_WAR_CRY, WARRIOR_SMITE, ROGUE_SET_SPIKE_TRAP, ROGUE_SET_EXPLODING_TRAP, ROGUE_SET_TIME_TRAP, ROGUE_EVASION, ROGUE_GREATER_EVASION, ROGUE_ASSASINATION, ROGUE_AVOID_DEATH, RANGER_TRACKING, PALADIN_SUMMON_DEVA, DRUID_IMMUNE_POISON, DRUID_RESISTS, SHADOWDANCER_SHADOW_TWIN, SHADOWDANCER_SHADOW_MAZE, SHADOWDANCER_SHADOW_FORM, SHAMAN_SPIRIT_FORM, SHAMAN_FAVORED_OF_THE_SPIRITS,
} from './spell.ids.d';

export type { State } from './state.ids.d';
export {
  STATE_NORMAL, STATE_DEAD, STATE_ACID_DEATH, STATE_FLAME_DEATH,
  STATE_EXPLODING_DEATH, STATE_STONE_DEATH, STATE_FROZEN_DEATH, STATE_HELPLESS,
  STATE_INVISIBLE, STATE_STUNNED, STATE_PANIC, STATE_BERSERK, STATE_SLEEPING,
  STATE_SILENCED, STATE_CHARMED, STATE_POISONED, STATE_HASTED, STATE_SLOWED,
  STATE_INFRAVISION, STATE_BLIND, STATE_DISEASED, STATE_FEEBLEMINDED,
  STATE_NONDETECTION, STATE_IMPROVEDINVISIBILITY, STATE_BLESS, STATE_CHANT,
  STATE_DRAWUPONHOLYMIGHT, STATE_LUCK, STATE_AID, STATE_CHANTBAD, STATE_BLUR,
  STATE_MIRRORIMAGE, STATE_CONFUSED, STATE_HARMLESS, STATE_RANGED_TARGET,
  STATE_OUT_OF_ACTION, STATE_NOT_VISIBLE, STATE_ENCHANTED, STATE_ILLUSIONS,
  STATE_INVALID,
} from './state.ids.d';

export type { Stats } from './stats.ids.d';
export type { TimeID } from './time.ids.d';
export type { TimeODay } from './timeoday.ids.d';

// --- Triggers (generated from IESDP) ---
export {
  Acquired, ActionListEmpty, ActuallyInCombat, Alignment, Allegiance,
  AmIInWatchersKeepPleaseIgnoreTheLackOfApostophe, AreaCheck, AreaCheckObject,
  AreaType, AttackedBy, BecameVisible, BreakingPoint, CalanderDay, CalanderDayGT,
  CalanderDayLT, CharName, CheckStat, CheckStatGT, CheckStatLT, Class, Clicked,
  Closed, CombatCounter, CombatCounterGT, CombatCounterLT, Contains,
  DamageTaken, DamageTakenGT, DamageTakenLT, Dead, Delay, Detect, Detected, Die,
  Died, Difficulty, DifficultyGT, DifficultyLT, Disarmed, DisarmFailed, Entered,
  Exists, FallenPaladin, FallenRanger, False, G, Gender, General, GGT, Global,
  GlobalGT, GlobalLT, GlobalsEqual, GlobalsGT, GlobalsLT, GlobalTimerExact,
  GlobalTimerExpired, GlobalTimerNotExpired, GLT, Happiness, HappinessGT,
  HappinessLT, HasBounceEffects, HasImmunityEffects, HasItem, HasItemEquiped,
  HasItemEquipedReal, HasItemSlot, HasWeaponEquiped, HaveAnySpells, HaveSpell,
  HaveSpellParty, HaveSpellRES, Heard, HitBy, HotKey, HP, HPGT, HPLT,
  HPPercent, HPPercentGT, HPPercentLT, IfValidForPartyDialog,
  IfValidForPartyDialogue, InActiveArea, InLine, InMyArea, InMyGroup, InParty,
  InPartyAllowDead, InPartySlot, InteractingWith, InventoryFull, InWatchersKeep,
  InWeaponRange, IsActive, IsGabber, IsOverMe, IsValidForPartyDialog,
  IsValidForPartyDialogue, Joins, Killed, Kit, Leaves, Level, LevelGT, LevelLT,
  LevelParty, LevelPartyGT, LevelPartyLT, LocalsEqual, LocalsGT, LocalsLT, LOS,
  ModalState, Morale, MoraleGT, MoraleLT, Name, NotStateCheck,
  NumberOfTimesTalkedTo, NumCreature, NumCreatureGT, NumCreatureLT,
  NumCreatureVsParty, NumCreatureVsPartyGT, NumCreatureVsPartyLT, NumDead,
  NumDeadGT, NumDeadLT, NumInParty, NumInPartyAlive, NumInPartyAliveGT,
  NumInPartyAliveLT, NumInPartyGT, NumInPartyLT, NumItems, NumItemsGT,
  NumItemsLT, NumItemsParty, NumItemsPartyGT, NumItemsPartyLT,
  NumTimesInteracted, NumTimesInteractedGT, NumTimesInteractedLT,
  NumTimesTalkedTo, NumTimesTalkedToGT, NumTimesTalkedToLT,
  ObjectActionListEmpty, OnCreation, OnScreen, Opened, OpenState, OR, OutOfAmmo,
  PartyGold, PartyGoldGT, PartyGoldLT, PartyHasItem, PartyHasItemIdentified,
  PartyMemberDied, PartyRested, PersonalSpaceDistance, PickLockFailed,
  PickPocketFailed, Race, RandomNum, RandomNumGT, RandomNumLT, Range, Reaction,
  ReactionGT, ReactionLT, RealGlobalTimerExact, RealGlobalTimerExpired,
  RealGlobalTimerNotExpired, ReceivedOrder, Reputation, ReputationGT,
  ReputationLT, Reset, Said, See, Specifics, SpellCast, SpellCastInnate,
  SpellCastOnMe, SpellCastPriest, StateCheck, StealFailed, Summoned,
  TargetUnreachable, Time, TimeGT, TimeLT, TimeOfDay, TimerExpired, TookDamage,
  TrapTriggered, Trigger, True, TurnedBy, Unlocked, UnselectableVariable,
  UnselectableVariableGT, UnselectableVariableLT, Unusable, WalkedToTrigger, XP,
  XPGT, XPLT,
} from './triggers';

export type { WeatherID } from './weather.ids.d';

// Help() is both an action and a trigger -- lives in a separate file.
export { Help } from './help.d';
