OUTER_SET EFF_effect_type = 0x0
OUTER_SET EFF_target = 0x2
OUTER_SET EFF_power = 0x3
OUTER_SET EFF_parameter1 = 0x4
OUTER_SET EFF_parameter2 = 0x8
OUTER_SET EFF_timing_mode = 0xc
OUTER_SET EFF_resistance = 0xd
OUTER_SET EFF_duration = 0xe
OUTER_SET EFF_probability1 = 0x12
OUTER_SET EFF_probability2 = 0x13
OUTER_SET EFF_resref_key = 0x14
OUTER_SET EFF_dice_thrown = 0x1c
OUTER_SET EFF_dice_sides = 0x20
OUTER_SET EFF_save_type = 0x24
OUTER_SET EFF_save_bonus = 0x28

